# Generated by Django 4.1.4 on 2023-05-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('ssylka', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pocupatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255, verbose_name='Наименование')),
                ('artikul', models.CharField(max_length=255, verbose_name='Артикул')),
                ('ssylka', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('opisanie', models.TextField(null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categoria', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Filter_product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Oil_product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('valume', models.CharField(max_length=255, verbose_name='Объем')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Carsina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colihestvo', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pocupatel', verbose_name='Пользователь')),
            ],
        ),
    ]
